# Generated by Django 2.2 on 2020-04-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDonor', models.BooleanField(default=False)),
                ('isReceiver', models.BooleanField(default=False)),
            ],
        ),
    ]
