# Generated by Django 2.2 on 2020-04-13 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='activeMedications',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='bloodGroup',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='comments',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='drugist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='isFrequent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='medications',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='username',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='DonorReceiverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dos', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
