# Generated by Django 2.2 on 2020-06-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0018_auto_20200625_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(default='', max_length=50)),
                ('to_user', models.CharField(default='', max_length=50)),
                ('date_sent', models.DateTimeField(auto_now=True, max_length=50)),
                ('message', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='DonorReceiverModel',
        ),
    ]
