# Generated by Django 2.2 on 2020-06-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0019_auto_20200626_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_typing',
            field=models.BooleanField(default=False),
        ),
    ]
