# Generated by Django 2.2 on 2020-07-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0021_auto_20200702_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_typing',
        ),
        migrations.AddField(
            model_name='clients',
            name='is_typing',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
