# Generated by Django 2.2 on 2020-07-12 19:53

import bloodapp.storage
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0024_auto_20200711_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, default='profile_photo/profile_image.jpg', height_field='image_height', storage=bloodapp.storage.OverwriteStorage(), upload_to='profile_photo', width_field='image_width'),
        ),
    ]
