# Generated by Django 2.2 on 2020-04-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0003_auto_20200429_0059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='UserInfoModel',
        ),
    ]
