# Generated by Django 2.2 on 2020-04-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0006_auto_20200430_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='blood_dr',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='medications',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
