# Generated by Django 2.2 on 2020-06-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0007_auto_20200430_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfomodel',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_image.jpg', upload_to='profile_photo'),
        ),
    ]
