# Generated by Django 2.2 on 2020-06-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0009_auto_20200624_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_image.jpg', height_field='200', max_length='100', upload_to='profile_photo', width_field='200'),
        ),
    ]
