# Generated by Django 2.2 on 2020-06-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0010_auto_20200624_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfomodel',
            name='image_height',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='userinfomodel',
            name='image_width',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_image.jpg', height_field='image_height', max_length='100', upload_to='profile_photo', width_field='image_width'),
        ),
    ]
