# Generated by Django 2.2 on 2020-06-25 07:16

import bloodapp.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0012_auto_20200624_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_image.jpg', height_field='image_height', storage=bloodapp.storage.OverwriteStorage(), upload_to='profile_photo', width_field='image_width'),
        ),
    ]
