# Generated by Django 2.2 on 2020-06-25 08:08

import bloodapp.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0014_auto_20200625_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_image.jpg', height_field='image_height', storage=bloodapp.storage.OverwriteStorage(), upload_to='profile_photo', width_field='image_width'),
        ),
    ]
