# Generated by Django 2.2 on 2020-07-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0022_auto_20200702_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activation_key',
            field=models.CharField(max_length=256),
        ),
    ]
